image: "python:3.7"

stages:
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - twine upload --repository-url --skip-existing $PYPRI_REPOSITORY_URL dist/* --verbose
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload --skip-existing dist/* --verbose
  only:
    - tags